const swaggerAutogen = require('swagger-autogen')({openapi: '3.0.0'})

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/routes/login.js', './src/routes/index.js' ]

const doc = {
    info: {
        version: "1.0.0",
        title: "Care Life Api",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        },

        {
            "name": "Organ",
            "description": "Endpoints"
        },

        {
            "name": "TypeOrgan",
            "description": "Endpoints"
        },

        {
            "name": "TypeUser",
            "description": "Endpoints"
        },

        {
            "name": "Login",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        bearerAuth: {
            type: 'http',
            scheme: 'bearer',
            bearerFormat: 'JWT'
        }
    }
}


swaggerAutogen(outputFile, endpointsFiles, doc);